spring:
  data:
    mongodb:
      database: agencies
      uri: mongodb://a:b@localhost:27017
      uuid-representation: standard

# comma separated list of allowed origins
allowed-origins: http://localhost:4200
